type Link {
    url: String!
    description: String!
    album: String!
    thumbnail: String
}

type Query {
    getAllAlbumLinks(album: String!): [Link!]!
    getLink(album: String!, description: String!): Link!
    getAllLinks: [Link!]!
}