[build]
    functions = "functions"
[[redirects]]
    from = "/api/getCeremonyLinks"
    to = "/.netlify/functions/getCeremonyLinks"
    status = 200
[[redirects]]
    from = "/api/getCoupleLinks"
    to = "/.netlify/functions/getCoupleLinks"
    status = 200