[build]
    functions = "functions"
[[redirects]]
    from = "/api/Ceremony"
    to = "/.netlify/functions/getCeremonyLinks"
    status = 200
[[redirects]]
    from = "/api/Couple"
    to = "/.netlify/functions/getCoupleLinks"
    status = 200
[[redirects]]
    from = "/api/Engagement"
    to = "/.netlify/functions/getEngagementLinks"
    status = 200
[[redirects]]
    from = "/api/GettingReady"
    to = "/.netlify/functions/getGettingReadyLinks"
    status = 200
[[redirects]]
    from = "/api/Family"
    to = "/.netlify/functions/getFamilyLinks"
    status = 200
[[redirects]]
    from = "/api/Reception"
    to = "/.netlify/functions/getReceptionLinks"
    status = 200
[[redirects]]
    from = "/api/Videos"
    to = "/.netlify/functions/getVideosLinks"
    status = 200
[[redirects]]
    from = "/api/Home"
    to = "/.netlify/functions/getHomeVideoLink"
    status = 200
[[redirects]]
    from = "/api/Puppies"
    to = "/.netlify/functions/getAllLinks"
    status = 200